version: '3.6'
services:
  nextcloud:
    image: linuxserver/nextcloud
    ports:
      - "127.0.0.1:12345:443"
    volumes:
      - /mnt/sdb/nextcloud/appdata:/config
      - /mnt/sdb/nextcloud/data:/data
    restart: unless-stopped

  synapse:
    container_name: synapse
    hostname: matrix.young-tw.com
    build:
        context: ../..
        dockerfile: docker/Dockerfile
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=matrix.young-tw.com
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_NO_TLS=1
      #- SYNAPSE_ENABLE_REGISTRATION=no
      #- SYNAPSE_CONFIG_PATH=/config
      # - SYNAPSE_LOG_LEVEL=DEBUG
      - SYNAPSE_REGISTRATION_SHARED_SECRET=afjeirkjl421
      - POSTGRES_DB=synapse
      - POSTGRES_HOST=db
      - POSTGRES_USER=young
      - POSTGRES_PASSWORD=afjeirkjl421
    volumes:
      - /Users/young/Code/config/server/docker/compose/app/synapse-data:/data
    depends_on:
      - db
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    ports:
      - 127.0.0.1:8448:8448/tcp

  joplin:
    image: joplin/server:latest
    depends_on:
        - db
    ports:
        - "127.0.0.1:22300:22300"
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=joplin.young-tw.com
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=afjeirkjl421
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=young
      - POSTGRES_PORT=8448
      - POSTGRES_HOST=db
    volumes:
      - /mnt/sdb/joplin:/data

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.young-tw.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.young-tw.com'
        # Add any other gitlab.rb configuration here, each on its own linea
    ports:
      - '12351:80'
      - '12352:22'
    volumes:
      - '/mnt/sdb/gitlab/config:/etc/gitlab'
      - '/mnt/sdb/gitlab/logs:/var/log/gitlab'
      - '/mnt/sdb/data:/var/opt/gitlab'
    shm_size: '256m'

  # yourls:
  #   image: yourls
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     YOURLS_DB_PASS: example
  #     YOURLS_SITE: https://url.young-tw.com
  #     YOURLS_USER: example_username
  #     YOURLS_PASS: example_password

  # gitlab:
  #   image: bitnami/gitlab-runner:latest
  #   ports:
  #     - "127.0.0.1:12346:80"
  #   volumes:
  #     - /home/young/gitlab/config:/etc/gitlab
  #     - /home/young/gitlab/logs:/var/log/gitlab
  #     - /home/young/gitlab/data:/var/opt/gitlab
  #   restart: unless-stopped

  # openvscode-server:
  #   image: lscr.io/linuxserver/openvscode-server:latest
  #   container_name: openvscode-server
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC+8
  #     - CONNECTION_TOKEN= #optional
  #     - CONNECTION_SECRET= #optional
  #     - SUDO_PASSWORD=password #optional
  #     - SUDO_PASSWORD_HASH= #optional
  #   volumes:
  #     - /path/to/appdata/config:/config
  #   ports:
  #     - "127.0.0.1:12348:3000"
  #   restart: unless-stopped

  # wireguard:
  #   image: linuxserver/wireguard

  db:
    container_name: postgres
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=young
      - POSTGRES_PASSWORD=afjeirkjl421
    volumes:
      - /var/lib/postgresql/data
    labels:
      - "traefik.enable=false"