version: '3.6'
services:
  young-bot:
    image: youngtw/dcbot:latest
    volumes:
      - ./young-bot:/app
    restart: unless-stopped

  young-studio:
    image: youngtw/dcbot-studio:latest
    volumes:
      - ./young-studio:/app
    restart: unless-stopped