version: '3.6'
services:
  nextcloud:
    image: nextcloud
    ports:
      - "127.0.0.1:12345:443"
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=snb395sbq
      - MYSQL_HOST=db
    volumes:
      - nextcloud_data:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=sntb395sbq
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=snb395sbq
    volumes:
      - /mnt/sdb/nextcloud/db:/var/lib/mysql

volumes:
  nextcloud_data:
  db_data:
