version: '3.6'
services:
  db:
    container_name: postgres
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  # mysql:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #    MYSQL_DATABASE: yourls
