version: '3.6'
services:
  synapse:
    container_name: synapse
    hostname: matrix.young-tw.com
    build:
        context: ../..
        dockerfile: docker/Dockerfile
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=matrix.young-tw.com
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_NO_TLS=1
      #- SYNAPSE_ENABLE_REGISTRATION=no
      #- SYNAPSE_CONFIG_PATH=/config
      # - SYNAPSE_LOG_LEVEL=DEBUG
      - SYNAPSE_REGISTRATION_SHARED_SECRET=afjeirkjl421
      - POSTGRES_DB=synapse
      - POSTGRES_HOST=db
      - POSTGRES_USER=young
      - POSTGRES_PASSWORD=afjeirkjl421
    volumes:
      - /Users/young/Code/config/server/docker/compose/app/synapse-data:/data
    depends_on:
      - db
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    ports:
      - 127.0.0.1:8448:8448/tcp

  db:
    container_name: postgres
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=young
      - POSTGRES_PASSWORD=afjeirkjl421
    volumes:
      - /var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
