version: '3.6'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 12359:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data