version: "3.9"

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/www/html
      - nextcloud-config:/var/www/html/config
    ports:
      - "127.0.0.1:12345:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - NEXTCLOUD_DATABASE_HOST=postgres
      - NEXTCLOUD_DATABASE_NAME=nextcloud
      - NEXTCLOUD_DATABASE_USER=nextcloud
      - NEXTCLOUD_DATABASE_PASSWORD=nextcloudpassword
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nextcloudpassword

volumes:
  nextcloud-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/sdb/nextcloud/config
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/sdb/nextcloud/postgres