version: '3'
services:
  blog:
    container_name: blog
    image: youngtw/blog:latest
    ports:
      - "127.0.0.1:12347:80"
    restart: unless-stopped

  link:
    container_name: link
    image: youngtw/link:latest
    ports:
      - "127.0.0.1:12348:3000"
    restart: unless-stopped

  # synpase:
  #   image: matrixdotorg/synapse:latest
  #   ports:
  #     - "8008:8008"
  #     - "8448:8448"
  #   volumes:
  #     - ./data:/data

  nextcloud:
    image: linuxserver/nextcloud
    ports:
      - "127.0.0.1:12345:443"
    volumes:
      - /mnt/sdb/nextcloud/appdata:/config
      - /mnt/sdb/nextcloud/data:/data
    restart: unless-stopped

  mc-website:
    image: youngtw/mc-website:latest
    ports:
      - "127.0.0.1:12349:3000"
    restart: unless-stopped

  # gitlab:
  #   image: bitnami/gitlab-runner:latest
  #   ports:
  #     - "127.0.0.1:12346:80"
  #   volumes:
  #     - /home/young/gitlab/config:/etc/gitlab
  #     - /home/young/gitlab/logs:/var/log/gitlab
  #     - /home/young/gitlab/data:/var/opt/gitlab
  #   restart: unless-stopped

  # openvscode-server:
  #   image: lscr.io/linuxserver/openvscode-server:latest
  #   container_name: openvscode-server
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC+8
  #     - CONNECTION_TOKEN= #optional
  #     - CONNECTION_SECRET= #optional
  #     - SUDO_PASSWORD=password #optional
  #     - SUDO_PASSWORD_HASH= #optional
  #   volumes:
  #     - /path/to/appdata/config:/config
  #   ports:
  #     - "127.0.0.1:12348:3000"
  #   restart: unless-stopped

  # wireguard:
  #   image: linuxserver/wireguard
