global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

api:
  dashboard: true
  insecure: true

# HTTPS 配置 (使用 Let's Encrypt 自動獲取 SSL 憑證)
certificatesResolvers:
  myresolver:
    acme:
      email: "your-email@example.com"  # 你的電子郵件地址
      storage: "/acme.json"  # 存儲 SSL 憑證的路徑
      httpChallenge:
        entryPoint: web

# 啟動服務
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"  # Docker socket 路徑
    watch: true
    exposedByDefault: false

# 啟用日誌
log:
  level: "INFO"  # 設置日誌級別