version: '3.6'
services:
  joplin:
    image: joplin/server:latest
    depends_on:
        - db
    ports:
        - "127.0.0.1:22300:22300"
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=joplin.young-tw.com
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=afjeirkjl421
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=young
      - POSTGRES_PORT=8448
      - POSTGRES_HOST=db
    volumes:
      - /mnt/sdb/joplin:/data